package jcrm.pp.ua.crmsystem.customClasses.registration;

public enum Privileges {

    CREATE_ACCOUNT_PRIVILEGE,
    READ_PRIVILEGE,
    WRITE_PRIVILEGE, DELETE_PRIVILEGE,
    CREATE_GUEST_PRIVILEGE, CREATE_USER_PRIVILEGE, DELETE_GUEST_PRIVILEGE, DELETE_USER_PRIVILEGE, BACK_UP_PRIVILEGE,
    PHYSICAL_BACK_UP_PRIVILEGE,
    CREATE_MANAGER_PRIVILEGE, CREATE_AUDITOR_PRIVILEGE, DELETE_MANAGER_PRIVILEGE, DELETE_AUDITOR_PRIVILEGE,
    DELETE_ACCOUNT_PRIVILEGE,BLOCK_ACCOUNT_PRIVILEGE,BACK_UP_ACCOUNT_PRIVILEGE

}
